In [2]:
import pandas as pd

In [3]:
simpsons = pd.read_html('https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes')

In [5]:
len(simpsons)

15

In [6]:
simpsons[1]

,Title,Directed by,Written by,Original release date
0,The Longest Daycare,David Silverman,"James L. Brooks, Matt Groening, Al Jean, David...","July 13, 2012"
1,Playdate with Destiny,David Silverman,"Al Jean, Tom Gammill, Max Pross, James L. Broo...","March 6, 2020"

# Website th scrape
https://www.football-data.co.uk/data.php

In [10]:
# read 1 csv file from the website
data_pl_25  = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [11]:
data_pl_25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,E0,15/03/2025,15:00,Southampton,Wolves,1,2,A,0,1,...,1.86,2.07,1.85,2.08,1.89,2.08,1.83,2.04,1.89,2.10
285,E0,15/03/2025,17:30,Bournemouth,Brentford,1,2,A,1,1,...,1.96,1.97,1.96,1.96,1.99,1.97,1.94,1.92,2.00,1.98
286,E0,16/03/2025,13:30,Arsenal,Chelsea,1,0,H,1,0,...,1.95,1.95,1.96,1.96,1.97,1.97,1.94,1.92,1.96,2.02
287,E0,16/03/2025,13:30,Fulham,Tottenham,2,0,H,0,0,...,1.84,2.06,1.85,2.08,1.86,2.09,1.84,2.02,1.90,2.10
288,E0,16/03/2025,19:00,Leicester,Man United,0,3,A,0,1,...,1.78,2.03,1.85,2.08,1.88,2.11,1.82,2.05,1.87,2.13